steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dataset-creation-mcp-server:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataset-creation-mcp-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dataset-creation-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dataset-creation-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600s'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'HF_TOKEN=${_HF_TOKEN}'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/dataset-creation-mcp-server:$COMMIT_SHA'

# Substitution variables to be provided during build
substitutions:
  _HF_TOKEN: '' # HuggingFace API token (to be set when triggering the build)

options:
  logging: CLOUD_LOGGING_ONLY 