steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/uk-legislation-mcp-server:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/uk-legislation-mcp-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'uk-legislation-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/uk-legislation-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/uk-legislation-mcp-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 